# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 94745d01815fb24a178c3fdb6e780d26629f60841e4d0cf2d97fdeef9cb3aacdeeb088578e5ca08fd71c317e399754c04e5d19872ec9c17dda52aa7708ffc458

test:
  secret_key_base: c56b59bb5ff46ff1a81e5ca43185dec1699921835d382380e72aa9f625d28d540674a4987f9de15e7acc19caff7036503a57901e3e5d8ab8a33af1286dcfa7bf

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
